# Generated by Django 4.1.7 on 2023-05-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
