# Generated by Django 4.1.7 on 2023-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0006_alter_profile_options_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
