# Generated by Django 4.1.7 on 2023-05-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0009_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
